<?php
$searchValue = $this->escapeHtml($this->params()->fromQuery('search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form" class="form-inline my-2 my-lg-0">
    <input type="text" name="search" value="<?php echo $searchValue; ?>" placeholder="<?php echo $this->translate('Search'); ?> " class="form-control mr-sm-2">
    <button type="submit" class="btn btn-outline-color1 my-2 my-sm-0"><?php echo $this->translate('Search'); ?></button>
</form>
