<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php //echo $this->pagination(); ?>
    <?php //echo $this->partial('common/sidebar-pagination'); ?>
    <?php //echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<div class="resource-list card-columns mt-2">
<?php
foreach ($items as $item):
    $heading = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
        
<div class="card rounded item resource">

      <?php echo $item->linkRaw($this->thumbnail($item, 'medium')); ?>


      <div class="card-body">
        <h5 class="card-title"><?php echo $item->link($heading, NULL,['class'=>'itemTitleLink']); ?></h5>
       <!-- <?php if ($body): ?><p class="card-text"><small class="text-muted"><?php echo $body; ?></small></p><?php endif; ?> -->
      </div>


</div>        

<?php endforeach; ?>
</div>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
