<?php
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');

$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));

$this->headLink()->appendStylesheet($this->assetUrl('css/main.css'));

$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');

$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));

$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    
<?php echo $this->htmlElement('body')->appendAttribute('class', 'container-fluid');; ?>
    
<main role="main" class="flex-shrink-0"> 

   
<div id="cabecalho" class="bg-dark"> 

    <div id="logotipoContainer" class="container">
    <div class="row">
        <div id="logotipo" class="col pl-0">
            <?php if ($this->themeSetting('logo')):?>
            <a href="<?php echo $site->url(); ?>"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>"></a> 
            <?php endif; ?>
        </div>
        <div id="tituloDaColecao" class="col-8 pr-0">
            <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
        </div>
    </div></div>
        
    


<nav id="mainMenu" class="navbar navbar-expand-lg navbar-dark bg-dark container">    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <?php
        echo $site->publicNav()->menu()->renderMenu(null, [
            'maxDepth' => $this->themeSetting('nav_depth') - 1,
            'ulClass' => 'navbar-nav mr-auto',
            'addPageClassToLi' => 'nav-item'
        ]);
        ?>

    </div>  
 
    <?php echo $this->partial('common/search-form'); ?>
</nav>
        
</div>           
    
    <div id="content" class="container mb-5">
        <?php echo $this->messages(); ?>
        <?php echo $this->content; ?>
    </div>
    
    <footer class="footer mt-3 bg-dark fixed-bottom">
        <div class="container">
            <span class="text-muted">
                Direitos Reservados © 2019<?php if (date('Y')>2019) echo '-'.date('Y'); ?> Instituto de Geociências - Universidade de São Paulo <br>
            </span>
        </div>
    </footer>     

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    
 
</main>
</body>
</html>
